global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'booking-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'kafka'
    static_configs:
      - targets: ['booking-kafka:9092']

  - job_name: 'redis'
    static_configs:
      - targets: ['booking-redis:6379']