spring:
  datasource:
    url: jdbc:postgresql://booking-postgres:5432/booking
    username: booking
    password: booking

  kafka:
    bootstrap-servers: booking-kafka:29092

  data:
    redis:
      host: booking-redis
      port: 6379

server:
  port: 8080